### ISSUE TITLE
Upgrade to Angular 13

### ISSUE THREAD

**Issue by cseas** [hypertrace/hyperdash-angular#659]
## Use Case

Angular 12 has reached end of life as of November 2022.

We're trying to upgrade a downstream repository (fork of hypertrace-ui) to Angular 13.
But getting a dependency conflict because hyperdash depends on Angular 12.

Reference PR: https://github.com/razorpay/hypertrace-ui/pull/119

We're using legacy-peer-deps option of npm as a workaround for this but would prefer to avoid it.

## Proposal

Upgrade hyperdash to use Angular 13.

**Comment by cseas** [comment]
@aaron-steinfeld @anandtiwary @itssharmasandeep

**Comment by itssharmasandeep** [comment]
There is a PR from @anandtiwary actually for angular 14. https://github.com/hypertrace/hyperdash-angular/pull/649
